# Generated by Django 4.1.5 on 2023-01-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmgd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
